import { db } from '@/lib/database/client';
import { albumMedia, media, mediaLike } from '@/lib/database/schemas';
import { user } from '@/lib/database/schemas/auth';
import { comment } from '@/lib/database/schemas/post';
import { cloudinary } from '@/lib/clients/cloudinary';
import { eq, and, desc, isNull, count, sql } from 'drizzle-orm';
import type { Media, MediaInsert } from '@/lib/database/types';
import { canUserUploadMedia, canUserDeleteMedia } from './permissions';

export interface UploadAvatarResult {
  id: string;
  url: string;
  width: number;
  height: number;
  fileSize: number;
  mimeType: string;
}

/**
 * Upload avatar image to Cloudinary and create media record
 */
export async function uploadAvatar(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string | null = null
): Promise<UploadAvatarResult> {
  // Upload to Cloudinary with transformations
  // Convert buffer to base64 data URI for Cloudinary upload
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/avatars',
    transformation: [
      { width: 512, height: 512, crop: 'fill' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Use provided MIME type (more accurate than inferring from format)

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId: tribeId || null,
    postId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Upload tribe avatar image to Cloudinary and create media record
 * Unlike uploadAvatar, this does NOT update the user's profile image
 */
export async function uploadTribeAvatar(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string | null = null
): Promise<UploadAvatarResult> {
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/avatars',
    transformation: [
      { width: 512, height: 512, crop: 'fill' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId,
    postId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Upload post image to Cloudinary and create media record
 */
export async function uploadPostImage(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string,
  postId: string | null = null
): Promise<UploadAvatarResult> {
  // Upload to Cloudinary with transformations
  // Convert buffer to base64 data URI for Cloudinary upload
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/posts',
    transformation: [
      { width: 1200, height: 1200, crop: 'limit' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId: tribeId || null,
    postId: postId || null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Upload tribe banner image to Cloudinary and create media record
 * Note: tribeId is optional since tribe may not exist yet during creation
 */
export async function uploadTribeBanner(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string | null = null
): Promise<UploadAvatarResult> {
  // Upload to Cloudinary with transformations optimized for banners (16:9)
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/banners',
    transformation: [
      { width: 1920, height: 1080, crop: 'limit' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId,
    postId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Upload event cover image to Cloudinary and create media record
 */
export async function uploadEventCover(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string
): Promise<UploadAvatarResult> {
  // Upload to Cloudinary with transformations
  // Convert buffer to base64 data URI for Cloudinary upload
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/events',
    transformation: [
      { width: 1200, height: 1200, crop: 'limit' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId,
    postId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Get media record by ID
 */
export async function getMediaById(id: string): Promise<Media | null> {
  const [mediaRecord] = await db
    .select()
    .from(media)
    .where(eq(media.id, id))
    .limit(1);

  return mediaRecord || null;
}

/**
 * Delete media from Cloudinary and database
 * @deprecated Use deleteMediaWithPermissions instead
 */
export async function deleteMedia(id: string): Promise<void> {
  const mediaRecord = await getMediaById(id);

  if (!mediaRecord) {
    return;
  }

  // Extract public_id from Cloudinary URL
  // Cloudinary URLs typically look like:
  // https://res.cloudinary.com/{cloud_name}/image/upload/{folder}/{filename}
  // We need to extract everything after /upload/ and remove the file extension
  const url = mediaRecord.fileUrl;
  const uploadIndex = url.indexOf('/upload/');
  if (uploadIndex === -1) {
    // If URL doesn't match expected format, try to delete from database anyway
    console.warn('Could not extract public_id from URL:', url);
    await db.delete(media).where(eq(media.id, id));
    return;
  }

  const pathAfterUpload = url.substring(uploadIndex + '/upload/'.length);
  // Remove file extension and any transformations
  // Split by '.' and take first part, then split by '/' to handle transformations
  const parts = pathAfterUpload.split('.');
  const publicId = parts[0];

  // Delete from Cloudinary
  try {
    await cloudinary.uploader.destroy(publicId);
  } catch (error) {
    console.error('Failed to delete from Cloudinary:', error);
    // Continue with database deletion even if Cloudinary deletion fails
  }

  // Delete from database
  await db.delete(media).where(eq(media.id, id));
}

/**
 * Delete media from Cloudinary and database with permission checks
 */
export async function deleteMediaWithPermissions(
  mediaId: string,
  tribeId: string,
  userId: string
): Promise<void> {
  // Check permissions
  const hasPermission = await canUserDeleteMedia(tribeId, userId, mediaId);
  if (!hasPermission) {
    throw new Error('User does not have permission to delete this media');
  }

  // Use existing deleteMedia function
  await deleteMedia(mediaId);
}

/**
 * Delete media without permission checks (for cleanup operations)
 * CAUTION: Only use for system cleanup (e.g., cancelled uploads)
 * @param mediaId - The media ID to delete
 */
export async function deleteMediaWithoutChecks(mediaId: string): Promise<void> {
  await deleteMedia(mediaId);
}

export interface MediaFilters {
  albumId?: string | null;
  type?: "image" | "video" | "document";
  limit?: number;
  offset?: number;
}

export interface UpdateMediaData {
  altText?: string;
  // Note: Album assignment is handled through the albumMedia junction table,
  // not through this interface. Use addMediaToAlbum() from album service instead.
}

/**
 * Get album media by tribe with filters
 * Selects from albumMedia table (album gallery items), not general media table
 * OPTIMIZED: Replaced N+1 subquery with LEFT JOIN for comment counts
 * @param tribeId - The tribe ID
 * @param filters - Optional filters for album media
 * @returns Array of album media records with like counts
 */
export async function getMediaByTribe(
  tribeId: string,
  filters: MediaFilters = {}
) {
  const { albumId, type, limit = 50, offset = 0 } = filters;

  // Build where conditions
  const conditions = [eq(media.tribeId, tribeId)];

  // Apply album filter
  if (albumId !== undefined) {
    if (albumId === null) {
      // Get general album items (albumId is null in albumMedia table)
      conditions.push(isNull(albumMedia.albumId));
    } else {
      // Get items in a specific album
      conditions.push(eq(albumMedia.albumId, albumId));
    }
  }

  if (type) {
    conditions.push(eq(media.fileType, type));
  }

  const query = db
    .select({
      id: albumMedia.id,
      mediaId: albumMedia.mediaId,
      fileUrl: media.fileUrl,
      fileType: media.fileType,
      fileSize: media.fileSize,
      mimeType: media.mimeType,
      width: media.width,
      height: media.height,
      duration: media.duration,
      thumbnailUrl: media.thumbnailUrl,
      altText: media.altText,
      createdAt: media.createdAt,
      uploadedBy: media.uploadedBy,
      postId: media.postId,
      albumId: albumMedia.albumId,
      addedAt: albumMedia.addedAt,
      tribeId: media.tribeId,
      uploader: {
        id: user.id,
        name: user.name,
        image: user.image,
      },
      likeCount: count(sql`DISTINCT ${mediaLike.id}`),
      commentCount: count(sql`DISTINCT ${comment.id}`),
    })
    .from(albumMedia)
    .leftJoin(media, eq(albumMedia.mediaId, media.id))
    .leftJoin(user, eq(media.uploadedBy, user.id))
    .leftJoin(mediaLike, eq(media.id, mediaLike.mediaId))
    .leftJoin(comment, eq(media.postId, comment.postId))
    .where(and(...conditions));

  const results = await query
    .groupBy(
      albumMedia.id,
      media.id,
      user.id,
    )
    .orderBy(desc(albumMedia.addedAt))
    .limit(limit)
    .offset(offset);

  return results;
}

/**
 * Get loose media (not in any album or post) for a tribe
 * @param tribeId - The tribe ID
 * @returns Array of media records not assigned to albums or posts
 */
export async function getLooseMedia(tribeId: string) {
  const results = await db
    .select({
      id: media.id,
      fileUrl: media.fileUrl,
      fileType: media.fileType,
      fileSize: media.fileSize,
      mimeType: media.mimeType,
      width: media.width,
      height: media.height,
      duration: media.duration,
      thumbnailUrl: media.thumbnailUrl,
      altText: media.altText,
      createdAt: media.createdAt,
      uploadedBy: media.uploadedBy,
      postId: media.postId,
      albumId: albumMedia.albumId,
      tribeId: media.tribeId,
      uploader: {
        id: user.id,
        name: user.name,
        image: user.image,
      },
      likeCount: count(mediaLike.id),
    })
    .from(media)
    .leftJoin(user, eq(media.uploadedBy, user.id))
    .leftJoin(mediaLike, eq(media.id, mediaLike.mediaId))
    .leftJoin(albumMedia, eq(media.id, albumMedia.mediaId))
    .where(
      and(
        eq(media.tribeId, tribeId),
        isNull(albumMedia.albumId),
        isNull(media.postId)
      )
    )
    .groupBy(media.id, user.id)
    .orderBy(desc(media.createdAt));

  return results;
}

/**
 * Get ALL media for a tribe (regardless of album membership)
 * Used for album cover selection and media browsing
 * @param tribeId - The tribe ID
 * @param options - Filter and pagination options
 * @returns Array of all media records for the tribe
 */
export async function getAllTribeMedia(
  tribeId: string,
  options: { type?: 'image' | 'video' | 'document'; limit?: number; offset?: number } = {}
) {
  const { type, limit = 100, offset = 0 } = options;

  const conditions = [eq(media.tribeId, tribeId)];
  if (type) {
    conditions.push(eq(media.fileType, type));
  }

  const results = await db
    .select({
      id: media.id,
      fileUrl: media.fileUrl,
      fileType: media.fileType,
      fileSize: media.fileSize,
      mimeType: media.mimeType,
      width: media.width,
      height: media.height,
      duration: media.duration,
      thumbnailUrl: media.thumbnailUrl,
      altText: media.altText,
      createdAt: media.createdAt,
      uploadedBy: media.uploadedBy,
      postId: media.postId,
      tribeId: media.tribeId,
      uploader: {
        id: user.id,
        name: user.name,
        image: user.image,
      },
      likeCount: count(sql`DISTINCT ${mediaLike.id}`),
      commentCount: count(sql`DISTINCT ${comment.id}`),
    })
    .from(media)
    .leftJoin(user, eq(media.uploadedBy, user.id))
    .leftJoin(mediaLike, eq(media.id, mediaLike.mediaId))
    .leftJoin(comment, eq(media.postId, comment.postId))
    .where(and(...conditions))
    .groupBy(media.id, user.id)
    .orderBy(desc(media.createdAt))
    .limit(limit)
    .offset(offset);

  return results;
}

/**
 * Update media
 * @param mediaId - The media ID
 * @param userId - The user ID (must be uploader or admin)
 * @param updateData - The data to update
 * @returns The updated media record
 */
export async function updateMedia(
  mediaId: string,
  userId: string,
  updateData: UpdateMediaData
) {
  // Get the media to check ownership
  const mediaRecord = await db
    .select()
    .from(media)
    .where(eq(media.id, mediaId))
    .limit(1);

  if (!mediaRecord[0]) {
    throw new Error("Media not found");
  }

  // Check if user is the uploader
  // TODO: Add check for admin/mod permissions
  if (mediaRecord[0].uploadedBy !== userId) {
    throw new Error("User does not have permission to update this media");
  }

  // Update the media
  const updated = await db
    .update(media)
    .set(updateData)
    .where(eq(media.id, mediaId))
    .returning();

  return updated[0];
}

/**
 * Like a media
 * @param mediaId - The media ID
 * @param userId - The user ID
 */
export async function likeMedia(mediaId: string, userId: string) {
  // Check if already liked
  const existing = await db
    .select()
    .from(mediaLike)
    .where(and(eq(mediaLike.mediaId, mediaId), eq(mediaLike.userId, userId)))
    .limit(1);

  if (existing[0]) {
    throw new Error("Media already liked");
  }

  // Create like
  const like = await db
    .insert(mediaLike)
    .values({
      mediaId,
      userId,
    })
    .returning();

  return like[0];
}

/**
 * Unlike a media
 * @param mediaId - The media ID
 * @param userId - The user ID
 */
export async function unlikeMedia(mediaId: string, userId: string) {
  // Delete the like
  await db
    .delete(mediaLike)
    .where(and(eq(mediaLike.mediaId, mediaId), eq(mediaLike.userId, userId)));
}

/**
 * Check if user has liked a media
 * @param mediaId - The media ID
 * @param userId - The user ID
 * @returns true if user has liked the media
 */
export async function hasUserLikedMedia(
  mediaId: string,
  userId: string
): Promise<boolean> {
  const result = await db
    .select()
    .from(mediaLike)
    .where(and(eq(mediaLike.mediaId, mediaId), eq(mediaLike.userId, userId)))
    .limit(1);

  return result.length > 0;
}

/**
 * Get total media count for a tribe
 * @param tribeId - The tribe ID
 * @returns The total number of media items
 */
export async function getTribeMediaCount(tribeId: string): Promise<number> {
  const result = await db
    .select({ count: count() })
    .from(media)
    .where(eq(media.tribeId, tribeId));

  return result[0]?.count || 0;
}

/**
 * Get total storage used by a tribe
 * @param tribeId - The tribe ID
 * @returns The total storage in bytes
 */
export async function getTribeStorageUsed(tribeId: string): Promise<number> {
  const result = await db
    .select({ total: sql<number>`SUM(${media.fileSize})` })
    .from(media)
    .where(eq(media.tribeId, tribeId));

  return result[0]?.total || 0;
}

/**
 * Upload media directly to tribe (not attached to post)
 */
export async function uploadTribeMedia(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string,
  albumId: string | null = null,
  addToAlbum: boolean = false
): Promise<UploadAvatarResult> {
  // Check permissions
  const hasPermission = await canUserUploadMedia(tribeId, userId);
  if (!hasPermission) {
    throw new Error('User does not have permission to upload media');
  }

  // Upload to Cloudinary with transformations
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/media',
    transformation: [
      { width: 1200, height: 1200, crop: 'limit' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId,
    postId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  if (addToAlbum === true) {
    await db.insert(albumMedia).values({
      albumId: albumId || null, // If albumId is null, the media will be added to the general album
      mediaId: createdMedia.id,
      addedBy: userId,
      addedAt: new Date(),
    });
  }

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Add media to an album via albumMedia junction table
 * @param mediaId - The media ID to add
 * @param albumId - The album ID (or null for general album)
 * @param userId - The user performing the action
 * @returns The created albumMedia record
 */
export async function addMediaToAlbumJunction(
  mediaId: string,
  albumId: string | null,
  userId: string
) {
  // Check if already exists
  const existing = await db
    .select()
    .from(albumMedia)
    .where(eq(albumMedia.mediaId, mediaId))
    .limit(1);

  if (existing[0]) {
    // Update existing albumMedia record
    const [updated] = await db
      .update(albumMedia)
      .set({ albumId: albumId })
      .where(eq(albumMedia.mediaId, mediaId))
      .returning();
    return updated;
  } else {
    // Create new albumMedia record
    const [created] = await db
      .insert(albumMedia)
      .values({
        albumId: albumId,
        mediaId: mediaId,
        addedBy: userId,
        addedAt: new Date(),
      })
      .returning();
    return created;
  }
}

/**
 * Remove media from all albums (delete albumMedia junction record)
 * @param mediaId - The media ID to remove
 */
export async function removeMediaFromAlbums(mediaId: string) {
  await db
    .delete(albumMedia)
    .where(eq(albumMedia.mediaId, mediaId));
}

/**
 * Update media album assignment
 * Handles adding to album, changing albums, or removing from albums
 * @param mediaId - The media ID
 * @param userId - The user ID (must be uploader or admin)
 * @param albumId - The album ID (null for general album, undefined to remove from all albums)
 * @param addToAlbum - Whether to add/keep in album (false removes from all albums)
 * @returns The updated albumMedia record or null if removed
 */
export async function updateMediaAlbumAssignment(
  mediaId: string,
  userId: string,
  albumId: string | null | undefined,
  addToAlbum: boolean
) {
  // Verify user owns the media
  const mediaRecord = await getMediaById(mediaId);
  if (!mediaRecord) {
    throw new Error("Media not found");
  }
  if (mediaRecord.uploadedBy !== userId) {
    throw new Error("User does not have permission to update this media");
  }

  if (addToAlbum) {
    // Add to album or change album
    return await addMediaToAlbumJunction(
      mediaId,
      albumId === undefined ? null : albumId,
      userId
    );
  } else {
    // Remove from all albums
    await removeMediaFromAlbums(mediaId);
    return null;
  }
}

