import { db } from '@/lib/database/client';
import { media } from '@/lib/database/schemas/media';
import { cloudinary } from '@/lib/clients/cloudinary';
import { eq } from 'drizzle-orm';
import type { Media, MediaInsert } from '@/lib/database/types';

export interface UploadAvatarResult {
  id: string;
  url: string;
  width: number;
  height: number;
  fileSize: number;
  mimeType: string;
}

/**
 * Upload avatar image to Cloudinary and create media record
 */
export async function uploadAvatar(
  fileBuffer: Buffer,
  userId: string,
  mimeType: string,
  tribeId: string | null = null
): Promise<UploadAvatarResult> {
  // Upload to Cloudinary with transformations
  // Convert buffer to base64 data URI for Cloudinary upload
  const base64Data = fileBuffer.toString('base64');
  const dataUri = `data:${mimeType};base64,${base64Data}`;

  const uploadResult = await cloudinary.uploader.upload(dataUri, {
    folder: 'tribes/avatars',
    transformation: [
      { width: 512, height: 512, crop: 'fill' },
      { quality: 'auto:good' },
      { fetch_format: 'auto' },
    ],
    resource_type: 'image',
  });

  // Use provided MIME type (more accurate than inferring from format)

  // Create media record
  const mediaData: Omit<MediaInsert, 'id' | 'createdAt'> = {
    fileUrl: uploadResult.secure_url,
    fileType: 'image',
    fileSize: uploadResult.bytes,
    mimeType,
    width: uploadResult.width,
    height: uploadResult.height,
    uploadedBy: userId,
    tribeId: tribeId || null,
    postId: null,
    albumId: null,
    duration: null,
    thumbnailUrl: null,
    altText: null,
  };

  const [createdMedia] = await db
    .insert(media)
    // @ts-ignore - id is auto-generated by defaultRandom()
    .values(mediaData as any)
    .returning();

  return {
    id: createdMedia.id,
    url: createdMedia.fileUrl,
    width: createdMedia.width || uploadResult.width,
    height: createdMedia.height || uploadResult.height,
    fileSize: createdMedia.fileSize || uploadResult.bytes,
    mimeType: createdMedia.mimeType || mimeType,
  };
}

/**
 * Get media record by ID
 */
export async function getMediaById(id: string): Promise<Media | null> {
  const [mediaRecord] = await db
    .select()
    .from(media)
    .where(eq(media.id, id))
    .limit(1);

  return mediaRecord || null;
}

/**
 * Delete media from Cloudinary and database
 */
export async function deleteMedia(id: string): Promise<void> {
  const mediaRecord = await getMediaById(id);
  
  if (!mediaRecord) {
    return;
  }

  // Extract public_id from Cloudinary URL
  const urlParts = mediaRecord.fileUrl.split('/');
  const filename = urlParts[urlParts.length - 1];
  const publicId = `tribes/avatars/${filename.split('.')[0]}`;

  // Delete from Cloudinary
  try {
    await cloudinary.uploader.destroy(publicId);
  } catch (error) {
    console.error('Failed to delete from Cloudinary:', error);
    // Continue with database deletion even if Cloudinary deletion fails
  }

  // Delete from database
  await db.delete(media).where(eq(media.id, id));
}

